import { Room } from './Room';

export const Rooms: Room[] = [
  {
    number: 101,
    name: 'Deluxe Room',
    description:
      'A luxurious room with a king-sized bed, ensuite bathroom, and a stunning view of the city.',
    price: 250,
    image: 'room1.jpeg',
    type: 'Deluxe',
    facility: ['wifi', 'Breakfast', 'Air conditioning', 'Gym access'],
    available: false,
  },
  {
    number: 102,
    name: 'Standard Room',
    description:
      'A comfortable room with a queen-sized bed and all standard amenities.',
    price: 150,
    image: 'room2.jpeg',
    type: 'Single',
    facility: ['wifi', 'Air conditioning'],
    available: true,
  },
  {
    number: 103,
    name: 'Suite',
    description:
      'A spacious suite with a separate living area, a king-sized bed, and premium amenities.',
    price: 400,
    image: 'room3.jpeg',
    type: 'Suite',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
    ],
    available: true,
  },
  {
    number: 104,
    name: 'Single Room',
    description: 'A cozy room with a single bed, perfect for solo travelers.',
    price: 100,
    image: 'room4.jpeg',
    type: 'Single',
    facility: ['wifi', 'Air conditioning'],
    available: false,
  },
  {
    number: 105,
    name: 'Double Room',
    description: 'A room with two double beds, ideal for families or groups.',
    price: 200,
    image: 'room5.jpeg',
    type: 'Single',
    facility: ['wifi', 'Air conditioning', 'breakfast'],
    available: true,
  },
  {
    number: 106,
    name: 'Business Suite',
    description:
      'A suite designed for business travelers, featuring a work desk and high-speed internet.',
    price: 300,
    type: 'Deluxe',
    image: 'room6.jpeg',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Meeting room',
    ],
    available: true,
  },
  {
    number: 107,
    name: 'Presidential Suite',
    description:
      'The most luxurious suite with premium amenities, a private balcony, and a breathtaking view.',
    price: 500,
    type: 'Suite',
    image: 'room7.jpeg',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
      'Private butler',
    ],
    available: true,
  },
  {
    number: 108,
    name: 'Economy Room',
    description:
      'A budget-friendly room with basic amenities and a comfortable bed.',
    price: 80,
    type: 'Single',
    image: 'room8.jpeg',
    facility: ['wifi', 'breakfast', 'Air conditioning'],
    available: false,
  },
  {
    number: 109,
    name: 'Family Room',
    description:
      'A large room with multiple beds, perfect for families traveling together.',
    price: 220,
    type: 'Suite',
    image: 'room9.jpeg',
    facility: ['wifi', 'breakfast', 'Air conditioning', 'Gym access'],
    available: true,
  },
  {
    number: 110,
    name: 'Honeymoon Suite',
    type: 'Suite',
    description:
      'A romantic suite with a king-sized bed, jacuzzi, and a beautiful view, perfect for honeymooners.',
    price: 350,
    image: 'room10.jpg',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
    ],
    available: false,
  },
  {
    number: 111,
    name: 'Executive Room',
    description:
      'A well-appointed room with a king-sized bed and workspace, ideal for business travelers.',
    price: 275,
    image: 'room11.jpeg',
    type: 'Deluxe',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Meeting room',
    ],
    available: true,
  },
  {
    number: 112,
    name: 'Junior Suite',
    description:
      'A stylish suite with a comfortable seating area and luxurious amenities.',
    price: 320,
    image: 'room12.jpeg',
    type: 'Suite',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
    ],
    available: true,
  },
  {
    number: 113,
    name: 'Penthouse Suite',
    description:
      'An opulent suite on the top floor, featuring panoramic views and exclusive amenities.',
    price: 600,
    image: 'room13.jpeg',
    type: 'Suite',
    facility: ['wifi', 'breakfast', 'Air conditioning', 'Gym access'],
    available: false,
  },
  {
    number: 114,
    name: 'Garden Room',
    description:
      'A charming room with a view of the hotel gardens and a private patio.',
    price: 200,
    image: 'room14.jpeg',
    type: 'Single',
    facility: ['wifi', 'Air conditioning', 'Private patio'],
    available: true,
  },
  {
    number: 115,
    name: 'Terrace Room',
    description:
      'A room with a private terrace offering stunning views and outdoor seating.',
    price: 230,
    image: 'room15.jpeg',
    type: 'Deluxe',
    facility: ['wifi', 'Air conditioning', 'Private terrace'],
    available: false,
  },
  {
    number: 116,
    name: 'Superior Room',
    description:
      'A spacious room with modern decor and enhanced amenities for added comfort.',
    price: 180,
    image: 'room16.jpeg',
    type: 'Deluxe',
    facility: [
      'wifi',
      'Air conditioning',
      'breakfast',
      'Gym access',
      'Spa services',
      'Private balcony',
    ],
    available: true,
  },
  {
    number: 117,
    name: 'Ocean View Suite',
    description:
      'A luxurious suite with a stunning view of the ocean, featuring a private balcony.',
    price: 450,
    image: 'room17.jpeg',
    type: 'Suite',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
      'Private balcony',
    ],
    available: true,
  },
  {
    number: 118,
    name: 'Mountain View Room',
    description:
      'A serene room with a beautiful view of the mountains and a cozy ambiance.',
    price: 210,
    image: 'room18.jpeg',
    type: 'Deluxe',
    facility: ['wifi', 'Air conditioning', 'breakfast', 'Private balcony'],
    available: true,
  },
  {
    number: 119,
    name: 'City View Room',
    description:
      'A room offering a spectacular view of the city skyline, perfect for urban travelers.',
    price: 190,
    image: 'room19.jpeg',
    type: 'Single',
    facility: ['wifi', 'Air conditioning', 'breakfast', 'Private balcony'],
    available: false,
  },
  {
    number: 120,
    name: 'Heritage Suite',
    description:
      'A suite with classic decor and historic charm, offering a unique and elegant stay.',
    price: 400,
    image: 'room20.jpeg',
    type: 'Suite',
    facility: [
      'wifi',
      'breakfast',
      'Air conditioning',
      'Gym access',
      'Spa services',
    ],
    available: true,
  },
];
